name: Deploy Backend to AWS EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/backend
            git pull origin main

            # 1. Limpieza de disco agresiva
            docker system prune -af

            # 2. Borramos la carpeta vendor si existe (por si está corrupta)
            # y borramos el archivo de bloqueo de docker para que empiece de cero
            rm -rf vendor
            
            # 3. Reinicio total
            docker compose down --remove-orphans
            docker compose up -d --build            
            
            # 4. Espera de seguridad para que el contenedor respire
            sleep 60
            
            # 5. Forzamos la instalación de librerías DESDE FUERA (para que no falle artisan)
            docker compose exec -T app composer install --no-dev --optimize-autoloader

            # 6. Ahora que ya existe 'vendor', artisan ya no dará error
            docker compose exec -T app php artisan migrate:fresh --seed --force
